-- MySQL Script generated by MySQL Workbench
-- Thu Oct 26 00:18:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`userInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userInfo` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `DOB` DATE NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `mail_id` VARCHAR(45) NOT NULL,
  `prof_pic` VARBINARY(50) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`userCredential`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userCredential` (
  `user_id` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`userInfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`SecurityQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SecurityQuestion` (
  `question_id` INT NOT NULL,
  `question` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`question_id`),
  UNIQUE INDEX `question_id_UNIQUE` (`question_id` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`UserSecurity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserSecurity` (
  `user_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `answer` LONGTEXT NOT NULL,
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `question_id_idx` (`question_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`userInfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`SecurityQuestion` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Friends` (
  `friend_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `freind_id_idx` (`friend_id` ASC),
  CONSTRAINT `friend_id`
    FOREIGN KEY (`friend_id`)
    REFERENCES `mydb`.`userInfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`userInfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Photo` (
  `user_id` INT NOT NULL,
  `description` LONGTEXT NULL,
  `time` DATETIME NOT NULL,
  `photo_id` INT NOT NULL,
  `photo_url` VARCHAR(45) NOT NULL,
  `photo` VARBINARY(70) NULL,
  PRIMARY KEY (`photo_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`userInfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Likes` (
  `user_id` INT NOT NULL,
  `photo_id` INT NOT NULL,
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `photo_id_idx` (`photo_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`userInfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `photo_id`
    FOREIGN KEY (`photo_id`)
    REFERENCES `mydb`.`Photo` (`photo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comments` (
  `user_id` INT NOT NULL,
  `photo_id` INT NOT NULL,
  `comments` LONGTEXT NULL,
  `time` DATETIME NULL,
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `photo_id_idx` (`photo_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`userInfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `photo_id`
    FOREIGN KEY (`photo_id`)
    REFERENCES `mydb`.`Photo` (`photo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tags` (
  `user_id` INT NOT NULL,
  `photo_id` INT NOT NULL,
  INDEX `photo_id_idx` (`photo_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`userInfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `photo_id`
    FOREIGN KEY (`photo_id`)
    REFERENCES `mydb`.`Photo` (`photo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Checkin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Checkin` (
  `user_id` INT NOT NULL,
  `photo_id` INT NOT NULL,
  `location` VARCHAR(45) NULL,
  `time` DATETIME NULL,
  INDEX `photo_id_idx` (`photo_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`userInfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `photo_id`
    FOREIGN KEY (`photo_id`)
    REFERENCES `mydb`.`Photo` (`photo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
