//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTestConsoleApp.PictreService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/UoW.Pictre.CoreService.DataTransferObject" +
        "s")]
    [System.SerializableAttribute()]
    public partial class UserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileImage {
            get {
                return this.ProfileImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileImageField, value) != true)) {
                    this.ProfileImageField = value;
                    this.RaisePropertyChanged("ProfileImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictreService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserByEmailID", ReplyAction="http://tempuri.org/IUserService/GetUserByEmailIDResponse")]
        WCFTestConsoleApp.PictreService.UserDto GetUserByEmailID(string EmailID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserByEmailID", ReplyAction="http://tempuri.org/IUserService/GetUserByEmailIDResponse")]
        System.Threading.Tasks.Task<WCFTestConsoleApp.PictreService.UserDto> GetUserByEmailIDAsync(string EmailID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUserByEmailID", ReplyAction="http://tempuri.org/IUserService/AddUserByEmailIDResponse")]
        int AddUserByEmailID(WCFTestConsoleApp.PictreService.UserDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUserByEmailID", ReplyAction="http://tempuri.org/IUserService/AddUserByEmailIDResponse")]
        System.Threading.Tasks.Task<int> AddUserByEmailIDAsync(WCFTestConsoleApp.PictreService.UserDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/TestGetEmpSalary", ReplyAction="http://tempuri.org/IUserService/TestGetEmpSalaryResponse")]
        string TestGetEmpSalary(string EmpId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/TestGetEmpSalary", ReplyAction="http://tempuri.org/IUserService/TestGetEmpSalaryResponse")]
        System.Threading.Tasks.Task<string> TestGetEmpSalaryAsync(string EmpId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/TestGetEmpSalaryPost", ReplyAction="http://tempuri.org/IUserService/TestGetEmpSalaryPostResponse")]
        string TestGetEmpSalaryPost(string EmpId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/TestGetEmpSalaryPost", ReplyAction="http://tempuri.org/IUserService/TestGetEmpSalaryPostResponse")]
        System.Threading.Tasks.Task<string> TestGetEmpSalaryPostAsync(string EmpId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : WCFTestConsoleApp.PictreService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<WCFTestConsoleApp.PictreService.IUserService>, WCFTestConsoleApp.PictreService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFTestConsoleApp.PictreService.UserDto GetUserByEmailID(string EmailID) {
            return base.Channel.GetUserByEmailID(EmailID);
        }
        
        public System.Threading.Tasks.Task<WCFTestConsoleApp.PictreService.UserDto> GetUserByEmailIDAsync(string EmailID) {
            return base.Channel.GetUserByEmailIDAsync(EmailID);
        }
        
        public int AddUserByEmailID(WCFTestConsoleApp.PictreService.UserDto user) {
            return base.Channel.AddUserByEmailID(user);
        }
        
        public System.Threading.Tasks.Task<int> AddUserByEmailIDAsync(WCFTestConsoleApp.PictreService.UserDto user) {
            return base.Channel.AddUserByEmailIDAsync(user);
        }
        
        public string TestGetEmpSalary(string EmpId) {
            return base.Channel.TestGetEmpSalary(EmpId);
        }
        
        public System.Threading.Tasks.Task<string> TestGetEmpSalaryAsync(string EmpId) {
            return base.Channel.TestGetEmpSalaryAsync(EmpId);
        }
        
        public string TestGetEmpSalaryPost(string EmpId) {
            return base.Channel.TestGetEmpSalaryPost(EmpId);
        }
        
        public System.Threading.Tasks.Task<string> TestGetEmpSalaryPostAsync(string EmpId) {
            return base.Channel.TestGetEmpSalaryPostAsync(EmpId);
        }
    }
}
