/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.1742)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [Pictre]    Script Date: 10/27/2017 11:25:28 PM ******/
CREATE DATABASE [Pictre]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Pictre', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Pictre.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Pictre_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Pictre_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Pictre] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pictre].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Pictre] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Pictre] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Pictre] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Pictre] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Pictre] SET ARITHABORT OFF 
GO

ALTER DATABASE [Pictre] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Pictre] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Pictre] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Pictre] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Pictre] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Pictre] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Pictre] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Pictre] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Pictre] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Pictre] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Pictre] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Pictre] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Pictre] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Pictre] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Pictre] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Pictre] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Pictre] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Pictre] SET RECOVERY FULL 
GO

ALTER DATABASE [Pictre] SET  MULTI_USER 
GO

ALTER DATABASE [Pictre] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Pictre] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Pictre] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Pictre] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Pictre] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Pictre] SET QUERY_STORE = OFF
GO

USE [Pictre]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Pictre] SET  READ_WRITE 
GO


