-- MySQL Script generated by MySQL Workbench
-- Thu Oct 26 00:18:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/* SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; */
/* SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; */
/* SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES'; */

-- -----------------------------------------------------
-- Schema Pictre
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pictre
-- -----------------------------------------------------

USE [Pictre];

-- -----------------------------------------------------
-- Table `Pictre`.`userInfo`
-- -----------------------------------------------------
CREATE TABLE [dbo].[User] (
  [user_id] INT NOT NULL IDENTITY,
  [user_name] VARCHAR(45) NOT NULL,
  [first_name] VARCHAR(45) NOT NULL,
  [last_name] VARCHAR(45) NULL,
  [DOB] DATE NOT NULL,
  [gender] VARCHAR(45) NOT NULL,
  [mail_id] VARCHAR(45) NOT NULL,
  [prof_pic] VARBINARY(50) NULL,
  PRIMARY KEY ([user_id]),
  CONSTRAINT [user_id_UNIQUE] UNIQUE  ([user_id] ASC),
  CONSTRAINT [user_name_UNIQUE] UNIQUE  ([user_name] ASC));


-- -----------------------------------------------------
-- Table `[dbo]`.`userCredential`
-- -----------------------------------------------------
CREATE TABLE [dbo].[UserCredential] (
  [user_id] INT NOT NULL,
  [password] VARCHAR(45) NOT NULL,
  CONSTRAINT [user_id]
    FOREIGN KEY ([user_id])
    REFERENCES [dbo].[User] ([user_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `[dbo]`.`SecurityQuestion`
-- -----------------------------------------------------
CREATE TABLE [dbo].[SecurityQuestion] (
  [question_id] INT NOT NULL,
  [question] VARCHAR(45) NOT NULL,
  PRIMARY KEY ([question_id]),
  CONSTRAINT [question_id_UNIQUE] UNIQUE  ([question_id] ASC));


-- -----------------------------------------------------
-- Table `[dbo]`.`UserSecurity`
-- -----------------------------------------------------
CREATE TABLE [dbo].[UserSecurity] (
  [user_id] INT NOT NULL,
  [question_id] INT NOT NULL,
  [answer] VARCHAR(max) NOT NULL
 ,
  CONSTRAINT [user_id]
    FOREIGN KEY ([user_id])
    REFERENCES [dbo].[User] ([user_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [question_id]
    FOREIGN KEY ([question_id])
    REFERENCES [dbo].SecurityQuestion ([question_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX [user_id_idx] ON [dbo].UserSecurity ([user_id] ASC);
CREATE INDEX [question_id_idx] ON [dbo].UserSecurity ([question_id] ASC);


-- -----------------------------------------------------
-- Table `[dbo]`.`Friends`
-- -----------------------------------------------------
CREATE TABLE [dbo].[Friends] (
  [friend_id] INT NOT NULL,
  [user_id] INT NOT NULL
 ,
  CONSTRAINT [friend_id]
    FOREIGN KEY ([friend_id])
    REFERENCES [dbo].[User] ([user_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [user_id]
    FOREIGN KEY ([user_id])
    REFERENCES [dbo].[User] ([user_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX [freind_id_idx] ON [dbo].Friends ([friend_id] ASC);


-- -----------------------------------------------------
-- Table `[dbo]`.`Photo`
-- -----------------------------------------------------
CREATE TABLE [dbo].[Photo] (
  [user_id] INT NOT NULL,
  [description] VARCHAR(max) NULL,
  [time] DATETIME2(0) NOT NULL,
  [photo_id] INT NOT NULL,
  [photo_url] VARCHAR(45) NOT NULL,
  [photo] VARBINARY(70) NULL,
  PRIMARY KEY ([photo_id])
 ,
  CONSTRAINT [user_id]
    FOREIGN KEY ([user_id])
    REFERENCES [dbo].[User] ([user_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX [user_id_idx] ON [dbo].Photo ([user_id] ASC);


-- -----------------------------------------------------
-- Table `[dbo]`.`Likes`
-- -----------------------------------------------------
CREATE TABLE [dbo].[Likes] (
  [user_id] INT NOT NULL,
  [photo_id] INT NOT NULL
 ,
  CONSTRAINT [user_id]
    FOREIGN KEY ([user_id])
    REFERENCES [dbo].[User] ([user_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [photo_id]
    FOREIGN KEY ([photo_id])
    REFERENCES [dbo].Photo ([photo_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX [user_id_idx] ON [dbo].Likes ([user_id] ASC);
CREATE INDEX [photo_id_idx] ON [dbo].Likes ([photo_id] ASC);


-- -----------------------------------------------------
-- Table `[dbo]`.`Comments`
-- -----------------------------------------------------
CREATE TABLE [dbo].[Comments] (
  [user_id] INT NOT NULL,
  [photo_id] INT NOT NULL,
  [comments] VARCHAR(max) NULL,
  [time] DATETIME2(0) NULL
 ,
  CONSTRAINT [user_id]
    FOREIGN KEY ([user_id])
    REFERENCES [dbo].[User] ([user_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [photo_id]
    FOREIGN KEY ([photo_id])
    REFERENCES [dbo].Photo ([photo_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX [user_id_idx] ON [dbo].Comments ([user_id] ASC);
CREATE INDEX [photo_id_idx] ON [dbo].Comments ([photo_id] ASC);


-- -----------------------------------------------------
-- Table `[dbo]`.`Tags`
-- -----------------------------------------------------
CREATE TABLE [dbo].[Tags] (
  [user_id] INT NOT NULL,
  [photo_id] INT NOT NULL
 ,
  CONSTRAINT [user_id]
    FOREIGN KEY ([user_id])
    REFERENCES [dbo].[User] ([user_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [photo_id]
    FOREIGN KEY ([photo_id])
    REFERENCES [dbo].Photo ([photo_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX [photo_id_idx] ON [dbo].Tags ([photo_id] ASC);
CREATE INDEX [user_id_idx] ON [dbo].Tags ([user_id] ASC);


-- -----------------------------------------------------
-- Table `[dbo]`.`Checkin`
-- -----------------------------------------------------
CREATE TABLE [dbo].[Checkin] (
  [user_id] INT NOT NULL,
  [photo_id] INT NOT NULL,
  [location] VARCHAR(45) NULL,
  [time] DATETIME2(0) NULL
 ,
  CONSTRAINT [user_id]
    FOREIGN KEY ([user_id])
    REFERENCES [dbo].[User] ([user_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [photo_id]
    FOREIGN KEY ([photo_id])
    REFERENCES [dbo].Photo ([photo_id])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX [photo_id_idx] ON [dbo].Checkin ([photo_id] ASC);
CREATE INDEX [user_id_idx] ON [dbo].Checkin ([user_id] ASC);


/* SET SQL_MODE=@OLD_SQL_MODE; */
/* SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; */
/* SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */
